name: Deploy to neocities

# only run on changes to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create folder
        run: |
          mkdir public
      - name: Clear folder
        run: |
          rm -rf public/*
      - name: Read folder
        run: |
          ls
      - name: Copy files
        run: | 
          cp -r ./ public/
      - uses: actions/checkout@v1
      # When the dist_dir is ready, deploy it to neocities
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: public
